# Generated by Django 5.2.4 on 2025-08-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CloudMisconfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("value", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ComplianceScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner", models.CharField(max_length=100)),
                ("score", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="IamRisk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=100)),
                ("privileges", models.CharField(max_length=100)),
                ("mfa_enabled", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="PackageHealth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("value", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="PackageVetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repository", models.CharField(max_length=100)),
                ("vulnerable_packages", models.IntegerField()),
                ("license_violations", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="RiskOverview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_issues", models.IntegerField()),
                ("high_risk_roles", models.IntegerField()),
                ("exposed_secrets", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SecretsHygiene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("secrets_found", models.IntegerField()),
                ("secrets_rotated", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SecurityAnomaly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("anomaly_type", models.CharField(max_length=100)),
                ("count", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ShadowIT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=100)),
                ("detected_on", models.DateField()),
            ],
        ),
    ]
